#ifndef CHARS_HPP
#define CHARS_HPP

#include <unordered_map>
#include <vector>

static constexpr bool o = false;
static           bool i = true; 

static std::unordered_map<char, std::vector<std::vector<bool>>> characters {
   {' ', {
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
   }}, {'!', {
      {o, i, i, o, o},
      {o, i, i, o, o},
      {o, i, i, o, o},
      {o, i, i, o, o},
      {o, i, i, o, o},
      {o, o, o, o, o},
      {o, i, i, o, o},
   }}, {'"', {
      {o, i, o, i, o},
      {o, i, o, i, o},
      {o, i, o, i, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
   }}, {'#', {
      {o, i, o, i, o},
      {i, i, i, i, i},
      {i, i, i, i, i},
      {o, i, o, i, o},
      {i, i, i, i, i},
      {i, i, i, i, i},
      {o, i, o, i, o},
   }}, {'$', {
      {o, i, i, i, o},
      {i, o, i, o, i},
      {i, o, i, o, o},
      {o, i, i, i, o},
      {o, o, i, o, i},
      {i, o, i, o, i},
      {o, i, i, i, o},
   }}, {'%', {
      {i, i, o, o, i},
      {i, i, o, i, o},
      {o, o, o, i, o},
      {o, o, i, o, o},
      {o, i, o, o, o},
      {o, i, o, i, i},
      {i, o, o, i, i},
   }}, {'&', {
      {o, i, i, o, o},
      {i, o, o, i, o},
      {i, o, o, i, o},
      {o, i, i, o, i},
      {i, o, o, i, i},
      {i, o, o, i, o},
      {o, i, i, o, i},
   }}, {'\'', {
      {o, o, i, o, o},
      {o, o, i, o, o},
      {o, o, i, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
   }}, {'(', {
      {o, o, i, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {o, o, i, o, o},
   }}, {')', {
      {o, o, i, o, o},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, i, o, o},
   }}, {'*', {
      {o, o, o, o, o},
      {i, o, i, o, i},
      {o, i, i, i, o},
      {i, i, i, i, i},
      {o, i, i, i, o},
      {i, o, i, o, i},
      {o, o, o, o, o},
   }}, {'+', {
      {o, o, o, o, o},
      {o, o, i, o, o},
      {o, o, i, o, o},
      {i, i, i, i, i},
      {o, o, i, o, o},
      {o, o, i, o, o},
      {o, o, o, o, o},
   }}, {',', {
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, i, i, o, o},
      {o, o, i, o, o},
   }}, {'-', {
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {i, i, i, i, i},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
   }}, {'.', {
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, i, i, o, o},
      {o, i, i, o, o},
   }}, {'/', {
      {o, o, o, o, i},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, i, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {i, o, o, o, o},
   }}, {'1', {
      {o, o, i, o, o},
      {o, i, i, o, o},
      {o, o, i, o, o},
      {o, o, i, o, o},
      {o, o, i, o, o},
      {o, o, i, o, o},
      {i, i, i, i, i},
   }}, {'2', {
      {o, i, i, i, o},
      {i, o, o, o, i},
      {o, o, o, o, i},
      {o, o, o, i, o},
      {o, o, i, o, o},
      {o, i, o, o, o},
      {i, i, i, i, i},
   }}, {'3', {
      {i, i, i, i, o},
      {o, o, o, o, i},
      {o, o, o, o, i},
      {i, i, i, i, o},
      {o, o, o, o, i},
      {o, o, o, o, i},
      {i, i, i, i, o},
   }}, {'4', {
      {i, o, o, o, i},
      {i, o, o, o, i},
      {i, o, o, o, i},
      {i, i, i, i, i},
      {o, o, o, o, i},
      {o, o, o, o, i},
      {o, o, o, o, i},
   }}, {'5', {
      {i, i, i, i, i},
      {i, o, o, o, o},
      {i, o, o, o, o},
      {i, i, i, i, o},
      {o, o, o, o, i},
      {o, o, o, o, i},
      {i, i, i, i, o},
   }}, {'6', {
      {o, i, i, i, o},
      {i, o, o, o, i},
      {i, o, o, o, o},
      {i, i, i, i, o},
      {i, o, o, o, i},
      {i, o, o, o, i},
      {o, i, i, i, o},
   }}, {'7', {
      {i, i, i, i, i},
      {o, o, o, o, i},
      {o, o, o, o, i},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, i, o, o},
      {o, o, i, o, o},
   }}, {'8', {
      {o, i, i, i, o},
      {i, o, o, o, i},
      {i, o, o, o, i},
      {o, i, i, i, o},
      {i, o, o, o, i},
      {i, o, o, o, i},
      {o, i, i, i, o},
   }}, {'9', {
      {o, i, i, i, o},
      {i, o, o, o, i},
      {i, o, o, o, i},
      {o, i, i, i, i},
      {o, o, o, o, i},
      {i, o, o, o, i},
      {o, i, i, i, o},
   }}, {'0', {
      {o, i, i, i, o},
      {i, o, o, i, i},
      {i, o, o, i, i},
      {i, o, i, o, i},
      {i, i, o, o, i},
      {i, i, o, o, i},
      {o, i, i, i, o},
   }}, {':', {
      {o, o, o, o, o},
      {o, i, i, o, o},
      {o, i, i, o, o},
      {o, o, o, o, o},
      {o, i, i, o, o},
      {o, i, i, o, o},
      {o, o, o, o, o},
   }}, {';', {
      {o, o, o, o, o},
      {o, i, i, o, o},
      {o, i, i, o, o},
      {o, o, o, o, o},
      {o, i, i, o, o},
      {o, o, i, o, o},
      {o, o, o, o, o},
   }}, {'<', {
      {o, o, o, o, o},
      {o, o, o, i, i},
      {o, i, i, o, o},
      {i, o, o, o, o},
      {o, i, i, o, o},
      {o, o, o, i, i},
      {o, o, o, o, o},
   }}, {'>', {
      {o, o, o, o, o},
      {i, i, o, o, o},
      {o, o, i, i, o},
      {o, o, o, o, i},
      {o, o, i, i, o},
      {i, i, o, o, o},
      {o, o, o, o, o},
   }}, {'=', {
      {o, o, o, o, o},
      {o, o, o, o, o},
      {i, i, i, i, i},
      {o, o, o, o, o},
      {i, i, i, i, i},
      {o, o, o, o, o},
      {o, o, o, o, o},
   }}, {'?', {
      {o, i, i, i, o},
      {i, o, o, i, i},
      {o, o, o, i, i},
      {o, i, i, i, o},
      {o, i, i, o, o},
      {o, o, o, o, o},
      {o, i, i, o, o},
   }}, {'@', {
      {o, i, i, i, o},
      {i, o, o, o, i},
      {i, o, i, o, i},
      {i, o, i, o, i},
      {i, o, i, i, i},
      {i, o, o, o, o},
      {o, i, i, i, o},
   }}, {'\\', {
      {i, o, o, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {o, o, i, o, o},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, o, o, i},
   }}, {'[', {
      {o, i, i, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {o, i, i, o, o},
   }}, {']', {
      {o, o, i, i, o},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, i, i, o},
   }}, {'^', {
      {o, o, i, o, o},
      {o, i, o, i, o},
      {o, i, o, i, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
   }}, {'_', {
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {i, i, i, i, i},
   }}, {'`', {
      {o, i, o, o, o},
      {o, o, i, o, o},
      {o, o, o, i, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
   }}, {'|', {
      {o, o, i, o, o},
      {o, o, i, o, o},
      {o, o, i, o, o},
      {o, o, i, o, o},
      {o, o, i, o, o},
      {o, o, i, o, o},
      {o, o, i, o, o},
   }}, {'~', {
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, i, i, o, i},
      {i, o, o, i, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
      {o, o, o, o, o},
   }}, {'{', {
      {o, o, i, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {i, i, o, o, o},
      {o, i, o, o, o},
      {o, i, o, o, o},
      {o, o, i, o, o},
   }}, {'}', {
      {o, o, i, o, o},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, o, i, i},
      {o, o, o, i, o},
      {o, o, o, i, o},
      {o, o, i, o, o},
   }},
};

#endif
